import os
from dotenv import load_dotenv

load_dotenv()

class Config:
    SECRET_KEY = os.getenv('SECRET_KEY')
    SQLALCHEMY_DATABASE_URI = os.getenv('SQLALCHEMY_DATABASE_URI')
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    JWT_SECRET_KEY = os.getenv('JWT_SECRET_KEY')
    AWS_ACCESS_KEY_ID=os.getenv('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY=os.getenv('AWS_SECRET_ACCESS_KEY')
    AWS_REGION=os.getenv('AWS_REGION')
    DYNAMODB_FILE_MANAGEMENT_TABLE_NAME=os.getenv('DYNAMODB_FILE_MANAGEMENT_TABLE_NAME')
    DYNAMODB_CONFIG_TABLE_NAME=os.getenv('DYNAMODB_CONFIG_TABLE_NAME')
    ENDPOINT_URL=os.getenv('ENDPOINT_URL')
    